server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/meu_banco
    username: usuario
    password: senha123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: fotos

