version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio

volumes:
  postgres_data:
  minio_data:
